#!/bin/bash

set -euo pipefail

cd $(dirname $0)

cmd="sbatch --mem 12G --time 2-0:0:0 slurm.sh"; moreargs=""
#export SLURM_JOBID=123456; cmd="python"; moreargs=""
#cmd=python; moreargs=runobs=0
#cmd="sbatch --mem 12G slurm.sh"; moreargs="onlyworkspace=1"

for scanrange in 101,-1,1 101,-0.02,0.02; do
 for which in expectvalues= runobs=0 ""; do
# for which in ""; do
  #default configuration
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg $which $moreargs

  #fix others
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 floatothers=0 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 floatothers=0 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 floatothers=0 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg floatothers=0 $which $moreargs

  #change fai order

  #fa3
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 faiorder=fa3,fL1,fL1Zg,fa1,fa2 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 faiorder=fa3,fa1,fa2,fL1,fL1Zg $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 faiorder=fa3,fa2,fL1Zg,fa1,fL1 $which $moreargs

  #fa2
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 faiorder=fa2,fL1,fa1,fL1Zg,fa3 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 faiorder=fa2,fL1,fa3,fa1,fL1Zg $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 faiorder=fa2,fL1Zg,fa3,fa1,fL1 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 faiorder=fa2,fa1,fL1,fa3,fL1Zg $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 faiorder=fa2,fa1,fL1Zg,fL1,fa3 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 faiorder=fa2,fa3,fL1,fa1,fL1Zg $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 faiorder=fa2,fa3,fL1Zg,fa1,fL1 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 faiorder=fa2,fa3,fa1,fL1Zg,fL1 $which $moreargs

  #fL1
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 faiorder=fL1,fL1Zg,fa1,fa3,fa2 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 faiorder=fL1,fL1Zg,fa3,fa1,fa2 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 faiorder=fL1,fa1,fL1Zg,fa2,fa3 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 faiorder=fL1,fa1,fL1Zg,fa3,fa2 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 faiorder=fL1,fa1,fa3,fL1Zg,fa2 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 faiorder=fL1,fa2,fa1,fL1Zg,fa3 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 faiorder=fL1,fa2,fa1,fa3,fL1Zg $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 faiorder=fL1,fa2,fa3,fa1,fL1Zg $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 faiorder=fL1,fa3,fa1,fL1Zg,fa2 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 faiorder=fL1,fa3,fa2,fa1,fL1Zg $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 faiorder=fL1,fL1Zg,fa1,fa2,fa3 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 faiorder=fL1,fL1Zg,fa3,fa2,fa1 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 faiorder=fL1,fL1Zg,fa2,fa3,fa1 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 faiorder=fL1,fL1Zg,fa2,fa1,fa3 $which $moreargs

  #fL1Zg
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg faiorder=fL1Zg,fL1,fa1,fa3,fa2 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg faiorder=fL1Zg,fL1,fa3,fa1,fa2 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg faiorder=fL1Zg,fa1,fa2,fL1,fa3 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg faiorder=fL1Zg,fa1,fa3,fL1,fa2 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg faiorder=fL1Zg,fa2,fa1,fa3,fL1 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg faiorder=fL1Zg,fa2,fa3,fa1,fL1 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg faiorder=fL1Zg,fa3,fL1,fa1,fa2 $which $moreargs
  $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg faiorder=fL1Zg,fa3,fa2,fa1,fL1 $which $moreargs

  #set input parameters

  if [ $scanrange == 101,-1,1 ]; then
    #fa3

    #fa2
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0,CMS_zz4l_fai3_relative:0.3,CMS_zz4l_fai4_relative:-0.8 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:0.1,CMS_zz4l_fai4_relative:-0.1 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:0.2,CMS_zz4l_fai4_relative:-1 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:0.3,CMS_zz4l_fai4_relative:-0.7 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.4,CMS_zz4l_fai3_relative:0.1,CMS_zz4l_fai4_relative:-1 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0,CMS_zz4l_fai3_relative:-0.025,CMS_zz4l_fai4_relative:0.9 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 faiorder=fa2,fa3,fL1,fa1,fL1Zg setparametersforgrid=CMS_zz4l_fa1_relative:0.18,CMS_zz4l_fai1_relative:0,CMS_zz4l_fai3_relative:0 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:0.3,CMS_zz4l_fai4_relative:-1 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0,CMS_zz4l_fai3_relative:0.2,CMS_zz4l_fai4_relative:-1 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0,CMS_zz4l_fai3_relative:0.23,CMS_zz4l_fai4_relative:-1 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0,CMS_zz4l_fai3_relative:0.26,CMS_zz4l_fai4_relative:-1 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0,CMS_zz4l_fai3_relative:-0.01,CMS_zz4l_fai4_relative:0.6 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0,CMS_zz4l_fai3_relative:-0.016,CMS_zz4l_fai4_relative:0.74 $which $moreargs

    #fL1
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0,CMS_zz4l_fai2_relative:-0.2,CMS_zz4l_fai4_relative:-1 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.3,CMS_zz4l_fai2_relative:0.1,CMS_zz4l_fai4_relative:-1 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.4,CMS_zz4l_fai2_relative:-0.1,CMS_zz4l_fai4_relative:0.1 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.4,CMS_zz4l_fai2_relative:-0.2,CMS_zz4l_fai4_relative:-0.5 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0,CMS_zz4l_fai2_relative:0.006,CMS_zz4l_fai4_relative:0.89 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0,CMS_zz4l_fai2_relative:0.005,CMS_zz4l_fai4_relative:0.82 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0,CMS_zz4l_fai2_relative:0.005,CMS_zz4l_fai4_relative:0.80 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0,CMS_zz4l_fai2_relative:0.004,CMS_zz4l_fai4_relative:0.74 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0,CMS_zz4l_fai2_relative:0.003,CMS_zz4l_fai4_relative:0.68 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0,CMS_zz4l_fai2_relative:0.002,CMS_zz4l_fai4_relative:0.62 $which $moreargs

    #fL1Zg
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0,CMS_zz4l_fai2_relative:-0.1,CMS_zz4l_fai3_relative:0.3 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0,CMS_zz4l_fai2_relative:-0.2,CMS_zz4l_fai3_relative:0.2 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0,CMS_zz4l_fai2_relative:-0.2,CMS_zz4l_fai3_relative:0.4 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-1,CMS_zz4l_fai3_relative:0.4 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg faiorder=fL1Zg,fL1,fa1,fa3,fa2 setparametersforgrid=CMS_zz4l_fai2_relative:-1,CMS_zz4l_fai3_relative:0.4 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg faiorder=fL1Zg,fa3,fa2,fa1,fL1 setparametersforgrid=CMS_zz4l_fai2_relative:-0.6,CMS_zz4l_fa1_relative:0 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.11,CMS_zz4l_fai2_relative:-0.03,CMS_zz4l_fai3_relative:1 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.12,CMS_zz4l_fai2_relative:-0.02,CMS_zz4l_fai3_relative:1 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0,CMS_zz4l_fai2_relative:-0.3,CMS_zz4l_fai3_relative:1 $which $moreargs
    $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0,CMS_zz4l_fai2_relative:-0.24,CMS_zz4l_fai3_relative:1 $which $moreargs
    #obs only
    if [ "$which" == expectvalues= ]; then

      #fa3

      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.002,CMS_zz4l_fai3_relative:-0.2,CMS_zz4l_fai4_relative:-0.038 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.002,CMS_zz4l_fai3_relative:-0.2,CMS_zz4l_fai4_relative:-0.05 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.002,CMS_zz4l_fai3_relative:-0.2,CMS_zz4l_fai4_relative:-0.063 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.002,CMS_zz4l_fai3_relative:-0.2,CMS_zz4l_fai4_relative:-0.075 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.002,CMS_zz4l_fai3_relative:-0.2,CMS_zz4l_fai4_relative:-0.088 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.002,CMS_zz4l_fai3_relative:-0.6,CMS_zz4l_fai4_relative:-0.15 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.002,CMS_zz4l_fai3_relative:-0.8,CMS_zz4l_fai4_relative:0.15 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.002,CMS_zz4l_fai3_relative:0.015,CMS_zz4l_fai4_relative:0.61 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.002,CMS_zz4l_fai3_relative:0.017,CMS_zz4l_fai4_relative:0.41 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.002,CMS_zz4l_fai3_relative:0.022,CMS_zz4l_fai4_relative:0.2 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.002,CMS_zz4l_fai3_relative:0.8,CMS_zz4l_fai4_relative:-0.3 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.002,CMS_zz4l_fai3_relative:0.8,CMS_zz4l_fai4_relative:-0.35 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.005,CMS_zz4l_fai3_relative:-0.8,CMS_zz4l_fai4_relative:-0.15 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.005,CMS_zz4l_fai3_relative:-0.8,CMS_zz4l_fai4_relative:-0.2 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.005,CMS_zz4l_fai3_relative:0.1,CMS_zz4l_fai4_relative:-0.67 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.008,CMS_zz4l_fai3_relative:0.14,CMS_zz4l_fai4_relative:0.23 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.008,CMS_zz4l_fai3_relative:0.6,CMS_zz4l_fai4_relative:-0.1 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.01,CMS_zz4l_fai3_relative:-0.2,CMS_zz4l_fai4_relative:0.76 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.01,CMS_zz4l_fai3_relative:0.14,CMS_zz4l_fai4_relative:0.7 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.2,CMS_zz4l_fai3_relative:0.12,CMS_zz4l_fai4_relative:-0.043 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.2,CMS_zz4l_fai3_relative:0.25,CMS_zz4l_fai4_relative:-0.12 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.22,CMS_zz4l_fai3_relative:-0.26 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.24,CMS_zz4l_fai3_relative:0.022,CMS_zz4l_fai4_relative:0.81 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.24,CMS_zz4l_fai4_relative:0.013 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.26,CMS_zz4l_fai3_relative:0.22,CMS_zz4l_fai4_relative:-0.087 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.26,CMS_zz4l_fai4_relative:0.54 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.28,CMS_zz4l_fai3_relative:0.021,CMS_zz4l_fai4_relative:0.28 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.28,CMS_zz4l_fai3_relative:0.14,CMS_zz4l_fai4_relative:0.032 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.28,CMS_zz4l_fai3_relative:0.28,CMS_zz4l_fai4_relative:-0.77 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.32,CMS_zz4l_fai3_relative:0.21,CMS_zz4l_fai4_relative:-0.093 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.32,CMS_zz4l_fai3_relative:0.88,CMS_zz4l_fai4_relative:-0.61 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.32,CMS_zz4l_fai3_relative:0.88,CMS_zz4l_fai4_relative:-0.74 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.34,CMS_zz4l_fai3_relative:-0.91,CMS_zz4l_fai4_relative:-0.51 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.34,CMS_zz4l_fai3_relative:-0.91,CMS_zz4l_fai4_relative:-0.84 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.34,CMS_zz4l_fai3_relative:0.24,CMS_zz4l_fai4_relative:0.02 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.34,CMS_zz4l_fai3_relative:0.61,CMS_zz4l_fai4_relative:-0.12 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.36,CMS_zz4l_fai3_relative:-0.94,CMS_zz4l_fai4_relative:0.52 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.36,CMS_zz4l_fai3_relative:0.22,CMS_zz4l_fai4_relative:-0.08 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.38,CMS_zz4l_fai3_relative:-0.65,CMS_zz4l_fai4_relative:-0.23 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.38,CMS_zz4l_fai3_relative:0.19,CMS_zz4l_fai4_relative:0.06 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.8,CMS_zz4l_fai3_relative:0.5,CMS_zz4l_fai4_relative:0.3 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.8,CMS_zz4l_fai3_relative:0.7,CMS_zz4l_fai4_relative:0.33 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:0.2,CMS_zz4l_fai3_relative:0.031 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:0.2,CMS_zz4l_fai4_relative:-0.088 $which $moreargs

      #fa2

      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:-0.22,CMS_zz4l_fai4_relative:-0.043 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:-0.22,CMS_zz4l_fai4_relative:-0.085 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:-0.22,CMS_zz4l_fai4_relative:-0.1 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:-0.22,CMS_zz4l_fai4_relative:-0.28 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:-0.22,CMS_zz4l_fai4_relative:-0.57 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:-0.22,CMS_zz4l_fai4_relative:-0.85 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:-0.22,CMS_zz4l_fai4_relative:0.014 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:-0.22,CMS_zz4l_fai4_relative:0.028 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:-0.22,CMS_zz4l_fai4_relative:0.043 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:-0.22,CMS_zz4l_fai4_relative:0.057 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:-0.44,CMS_zz4l_fai4_relative:0.79 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:-0.67,CMS_zz4l_fai4_relative:0.067 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:0.022,CMS_zz4l_fai4_relative:-0.034 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:0.022,CMS_zz4l_fai4_relative:0.23 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:0.11,CMS_zz4l_fai4_relative:-1.0 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:0.22,CMS_zz4l_fai4_relative:-0.28 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:0.22,CMS_zz4l_fai4_relative:-0.57 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai3_relative:-0.25,CMS_zz4l_fai4_relative:-0.33 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai3_relative:-0.75,CMS_zz4l_fai4_relative:-0.35 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai3_relative:0.021,CMS_zz4l_fai4_relative:0.013 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai3_relative:0.12,CMS_zz4l_fai4_relative:-0.85 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai3_relative:0.18,CMS_zz4l_fai4_relative:-0.61 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai3_relative:0.22,CMS_zz4l_fai4_relative:0.016 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai3_relative:0.22,CMS_zz4l_fai4_relative:0.064 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai4_relative:0.037 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai4_relative:0.75 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.2 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai3_relative:-0.8 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai3_relative:0.015,CMS_zz4l_fai4_relative:0.2 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai3_relative:0.022,CMS_zz4l_fai4_relative:-0.072 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai3_relative:0.14,CMS_zz4l_fai4_relative:0.047 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai3_relative:0.18,CMS_zz4l_fai4_relative:0.98 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai3_relative:0.6,CMS_zz4l_fai4_relative:-0.1 $which $moreargs

      #fL1

      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai4_relative:-0.033 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai4_relative:-0.056 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai4_relative:-0.067 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai4_relative:-0.078 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai4_relative:-0.22 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai4_relative:-0.67 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai4_relative:0.022 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai4_relative:0.045 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai4_relative:0.22 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai4_relative:0.45 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai4_relative:0.67 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai4_relative:0.89 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0089,CMS_zz4l_fai4_relative:-0.45 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.42,CMS_zz4l_fai4_relative:0.038 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.89,CMS_zz4l_fai4_relative:-0.3 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.89,CMS_zz4l_fai4_relative:-0.4 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:0.22,CMS_zz4l_fai4_relative:0.014 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:0.67,CMS_zz4l_fai4_relative:0.1 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai2_relative:-0.0025,CMS_zz4l_fai4_relative:0.038 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai2_relative:-0.0062,CMS_zz4l_fai4_relative:-0.25 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai2_relative:-0.45,CMS_zz4l_fai4_relative:-0.14 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai2_relative:-0.47,CMS_zz4l_fai4_relative:-0.47 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai2_relative:-0.5,CMS_zz4l_fai4_relative:0.05 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai2_relative:-0.5,CMS_zz4l_fai4_relative:0.1 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai2_relative:0.75,CMS_zz4l_fai4_relative:-0.35 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai2_relative:-0.005,CMS_zz4l_fai4_relative:-0.6 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai2_relative:-0.008,CMS_zz4l_fai4_relative:0.81 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai2_relative:-0.22,CMS_zz4l_fai4_relative:-0.26 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai2_relative:-0.32,CMS_zz4l_fai4_relative:-0.29 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai2_relative:-0.34,CMS_zz4l_fai4_relative:-0.91 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai2_relative:-0.36,CMS_zz4l_fai4_relative:0.047 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai2_relative:-0.38,CMS_zz4l_fai4_relative:0.65 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai2_relative:-0.8,CMS_zz4l_fai4_relative:-0.3 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai2_relative:-0.8,CMS_zz4l_fai4_relative:-0.35 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai2_relative:-0.8 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai2_relative:0.4,CMS_zz4l_fai4_relative:0.67 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai2_relative:0.6,CMS_zz4l_fai4_relative:-0.1 $which $moreargs

      #fL1Zg

      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai3_relative:-0.22 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai3_relative:-0.45 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai3_relative:-0.67 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai3_relative:-0.89 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai3_relative:0.017 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai3_relative:0.022 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai3_relative:0.024 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai3_relative:0.028 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai3_relative:0.11 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai3_relative:0.67 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.22,CMS_zz4l_fai3_relative:-0.85 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.24,CMS_zz4l_fai3_relative:0.26 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.24,CMS_zz4l_fai3_relative:0.58 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.31,CMS_zz4l_fai3_relative:-0.32 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.4,CMS_zz4l_fai3_relative:-0.74 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.44,CMS_zz4l_fai3_relative:0.04 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:0.44,CMS_zz4l_fai3_relative:-0.79 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:0.44,CMS_zz4l_fai3_relative:0.32 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:0.67,CMS_zz4l_fai3_relative:0.057 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai2_relative:-0.0062,CMS_zz4l_fai3_relative:0.5 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai2_relative:-0.01,CMS_zz4l_fai3_relative:0.13 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai2_relative:-0.47,CMS_zz4l_fai3_relative:0.052 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai2_relative:0.25,CMS_zz4l_fai3_relative:0.2 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.005,CMS_zz4l_fai3_relative:0.02 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.2,CMS_zz4l_fai3_relative:-0.25 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.24,CMS_zz4l_fai3_relative:-0.26 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.3,CMS_zz4l_fai3_relative:0.86 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.32,CMS_zz4l_fai3_relative:0.18 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.34,CMS_zz4l_fai3_relative:-0.91 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.36,CMS_zz4l_fai3_relative:-0.94 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.6,CMS_zz4l_fai3_relative:-1.0 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:0.2,CMS_zz4l_fai3_relative:0.75 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai3_relative:0.4 $which $moreargs
    #exp only
    elif [ "$which" == runobs=0 ]; then
      true
    elif [ "$which" == "" ]; then
      true
    else
      echo "unknown which $which"; exit 1
    fi

  elif [ $scanrange == 101,-0.02,0.02 ]; then
    #obs only
    if [ "$which" == expectvalues= ]; then

      #fa3

      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.002,CMS_zz4l_fai3_relative:-0.2,CMS_zz4l_fai4_relative:-0.038 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.002,CMS_zz4l_fai3_relative:-0.2,CMS_zz4l_fai4_relative:-0.05 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.01,CMS_zz4l_fai3_relative:0.4,CMS_zz4l_fai4_relative:-0.1 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.2,CMS_zz4l_fai3_relative:-0.5,CMS_zz4l_fai4_relative:0.025 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.2,CMS_zz4l_fai3_relative:-0.75,CMS_zz4l_fai4_relative:1.0 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.22,CMS_zz4l_fai3_relative:-0.26,CMS_zz4l_fai4_relative:0.69 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.22,CMS_zz4l_fai3_relative:-0.51,CMS_zz4l_fai4_relative:0.026 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.22,CMS_zz4l_fai3_relative:0.028,CMS_zz4l_fai4_relative:0.26 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.26,CMS_zz4l_fai3_relative:-0.27,CMS_zz4l_fai4_relative:0.074 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.26,CMS_zz4l_fai3_relative:-0.81,CMS_zz4l_fai4_relative:0.28 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.26,CMS_zz4l_fai3_relative:0.027,CMS_zz4l_fai4_relative:-0.069 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.26,CMS_zz4l_fai3_relative:0.027,CMS_zz4l_fai4_relative:-0.097 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.3,CMS_zz4l_fai3_relative:0.86,CMS_zz4l_fai4_relative:0.1 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.32,CMS_zz4l_fai3_relative:0.029,CMS_zz4l_fai4_relative:0.015 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.32,CMS_zz4l_fai3_relative:0.037,CMS_zz4l_fai4_relative:-0.061 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.32,CMS_zz4l_fai3_relative:0.037,CMS_zz4l_fai4_relative:-0.92 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.32,CMS_zz4l_fai3_relative:0.88,CMS_zz4l_fai4_relative:0.25 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.34,CMS_zz4l_fai3_relative:-0.91,CMS_zz4l_fai4_relative:-0.51 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.34,CMS_zz4l_fai3_relative:-0.91,CMS_zz4l_fai4_relative:-0.67 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.34,CMS_zz4l_fai3_relative:0.026,CMS_zz4l_fai4_relative:-0.31 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.34,CMS_zz4l_fai3_relative:0.91,CMS_zz4l_fai4_relative:0.17 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.34,CMS_zz4l_fai3_relative:0.91,CMS_zz4l_fai4_relative:0.34 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.36,CMS_zz4l_fai3_relative:0.023,CMS_zz4l_fai4_relative:0.96 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.38,CMS_zz4l_fai3_relative:-0.65,CMS_zz4l_fai4_relative:-0.14 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.38,CMS_zz4l_fai3_relative:0.65,CMS_zz4l_fai4_relative:-0.92 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.6,CMS_zz4l_fai3_relative:-0.5,CMS_zz4l_fai4_relative:0.2 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.6,CMS_zz4l_fai3_relative:0.037,CMS_zz4l_fai4_relative:0.1 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.6,CMS_zz4l_fai3_relative:0.043,CMS_zz4l_fai4_relative:0.52 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.6,CMS_zz4l_fai3_relative:0.05,CMS_zz4l_fai4_relative:0.11 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.6,CMS_zz4l_fai3_relative:0.062,CMS_zz4l_fai4_relative:0.11 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.6,CMS_zz4l_fai3_relative:0.35,CMS_zz4l_fai4_relative:0.038 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.6,CMS_zz4l_fai3_relative:0.4,CMS_zz4l_fai4_relative:0.17 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:-0.8,CMS_zz4l_fai3_relative:0.9,CMS_zz4l_fai4_relative:1.0 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa3 setparametersforgrid=CMS_zz4l_fai2_relative:0.2,CMS_zz4l_fai3_relative:0.75,CMS_zz4l_fai4_relative:0.05 $which $moreargs

      #fa2

      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:-0.22,CMS_zz4l_fai4_relative:-0.057 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:-0.22,CMS_zz4l_fai4_relative:-0.071 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:-0.22,CMS_zz4l_fai4_relative:-0.085 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:-0.22,CMS_zz4l_fai4_relative:-0.1 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:-0.22,CMS_zz4l_fai4_relative:-0.57 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:-0.22,CMS_zz4l_fai4_relative:-0.85 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:-0.22,CMS_zz4l_fai4_relative:0.014 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:-0.22,CMS_zz4l_fai4_relative:0.028 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:0.017,CMS_zz4l_fai4_relative:-0.9 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai3_relative:0.16 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai3_relative:-0.25,CMS_zz4l_fai4_relative:-0.12 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai4_relative:0.05 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai3_relative:0.02,CMS_zz4l_fai4_relative:-0.051 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai3_relative:0.022,CMS_zz4l_fai4_relative:0.02 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai3,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fa2 setparametersforgrid=CMS_zz4l_fai3_relative:0.14,CMS_zz4l_fai4_relative:0.47 $which $moreargs

      #fL1

      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai4_relative:-0.033 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai4_relative:-0.056 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai4_relative:-0.078 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai4_relative:-0.89 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai4_relative:0.011 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai4_relative:0.022 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai4_relative:0.033 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai4_relative:0.22 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai4_relative:0.45 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai4_relative:0.67 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai4_relative:0.89 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.22,CMS_zz4l_fai4_relative:-0.85 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.42 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai2_relative:-0.37 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai2_relative:-0.47,CMS_zz4l_fai4_relative:-0.47 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai2_relative:-0.5,CMS_zz4l_fai4_relative:-1.0 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai2_relative:-0.26,CMS_zz4l_fai4_relative:-0.068 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai2_relative:-0.26,CMS_zz4l_fai4_relative:-0.54 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai2_relative:-0.34,CMS_zz4l_fai4_relative:-0.61 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai4,CMS_zz4l_fa1 scanfai=fL1 setparametersforgrid=CMS_zz4l_fai2_relative:-0.8,CMS_zz4l_fai4_relative:0.05 $which $moreargs

      #fL1Zg

      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai3_relative:-0.22 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai3_relative:-0.45 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai3_relative:-0.67 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai3_relative:-0.89 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai3_relative:0.017 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai3_relative:0.019 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai3_relative:0.022 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai3_relative:0.024 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai3_relative:0.028 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai3_relative:0.11 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022,CMS_zz4l_fai3_relative:0.13 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.0022 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.24,CMS_zz4l_fai3_relative:0.037 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.4,CMS_zz4l_fai3_relative:0.26 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.1,CMS_zz4l_fai2_relative:-0.67,CMS_zz4l_fai3_relative:0.057 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai2_relative:-0.01,CMS_zz4l_fai3_relative:0.019 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai2_relative:-0.25,CMS_zz4l_fai3_relative:0.27 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai2_relative:-0.25,CMS_zz4l_fai3_relative:0.2 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai2_relative:-0.33,CMS_zz4l_fai3_relative:0.028 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai2_relative:-0.37,CMS_zz4l_fai3_relative:0.36 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai2_relative:-0.37 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.2,CMS_zz4l_fai3_relative:0.031 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.002,CMS_zz4l_fai3_relative:-0.6 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.005,CMS_zz4l_fai3_relative:0.017 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.008,CMS_zz4l_fai3_relative:0.015 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.008,CMS_zz4l_fai3_relative:0.017 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.008,CMS_zz4l_fai3_relative:0.025 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.01,CMS_zz4l_fai3_relative:0.015 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.01,CMS_zz4l_fai3_relative:0.02 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.2,CMS_zz4l_fai3_relative:0.019 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.2,CMS_zz4l_fai3_relative:0.027 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.2,CMS_zz4l_fai3_relative:0.031 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.22,CMS_zz4l_fai3_relative:0.13 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.22 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.24,CMS_zz4l_fai3_relative:0.033 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.28 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.3,CMS_zz4l_fai3_relative:0.86 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.32,CMS_zz4l_fai3_relative:-0.59 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:-0.34,CMS_zz4l_fai3_relative:0.033 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai2_relative:0.2,CMS_zz4l_fai3_relative:-0.25 $which $moreargs

      #more fL1Zg
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai1_relative:0.01,CMS_zz4l_fai2_relative:-0.2,CMS_zz4l_fai3_relative:0.25 $which $moreargs
      $cmd ./step9_runcombine.py fa3fa2fL1fL1Zg_morecategories finalforthesis scanranges=$scanrange plotnuisances=CMS_zz4l_fai1,CMS_zz4l_fai2,CMS_zz4l_fai3,CMS_zz4l_fa1 scanfai=fL1Zg setparametersforgrid=CMS_zz4l_fai3_relative:0.05 $which $moreargs

    #exp only
    elif [ "$which" == runobs=0 ]; then
      true
    elif [ "$which" == "" ]; then
      true
    else
      echo "unknown which $which"; exit 1
    fi
  elif [ $scanrange == 101,-1,1:101,-0.02,0.02 ]; then
    true
  else
    echo "Bad scanrange $scanrange"
    exit 1
  fi
 done
done
